version: "1.0"
info:
  model: int-scaffold
packages:
- name: ICUI_AutomaionProject0109Project
  gitServerName: ICAccount0109
  gitUrl: https://github.com/MeghaRaj69/ICUI_AutomaionProject0109Project
  gitUsername: MeghaRaj69
  gitBranch: main
